<?php include VIEW . 'rm' . DIRECTORY_SEPARATOR . 'header.phtml'; 
$ch = $this->get_view_data() ;

$prev = $ch['characters']['info']['prev'];
$next = $ch['characters']['info']['next'];
$characters = $ch['characters']['info']['count'];
$pages = $ch['characters']['info']['pages'];

?>

<div class="container">
    <div class="row">
    
    
    	<div class="col-3 p-5"> 
    		 <img src="https://scontent-lhr8-1.cdninstagram.com/v/t51.2885-19/s150x150/119705016_996089834243488_7643013248683499256_n.jpg?_nc_ht=scontent-lhr8-1.cdninstagram.com&_nc_ohc=IHgScAqfKMMAX8WhkcF&oh=7ce57cc7683a4e6891be20aa13d5f6eb&oe=5FC5F42A" 
    		 		class="rounded-circle"
    		 />
    	</div>
    	
    	<div class="col-9 pt-5">
    	
    		 <div class="d-flex justify-content-between align-items-baseline" >
    		 <h1>Characters</h1>
    		 </div>
    		 
    		 <div class="d-flex">
        		 <div class="pr-5"><strong><?php echo $characters?></strong> characters</div>
        		 <div class="pr-5"><strong><?php echo $pages?></strong> pages</div>
    		 </div>
	 
    		 <div class="pt-4 font-weight-bold">Regions</div>
    		 <div>Locations</div>
    		 <div>Episodes</div>
    		 
    	</div>
    	
    	
    	
    </div>
    

    <?php include VIEW . 'rm' . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
    
	<?php include VIEW . 'rm' . DIRECTORY_SEPARATOR . 'imagerow.phtml'; ?>
    
    <?php include VIEW . 'rm' . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
</div>






<?php include VIEW . 'rm' . DIRECTORY_SEPARATOR . 'footer.phtml'; 