<!doctype html>

<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<script async src="https://cse.google.com/cse.js?cx=b3f4a7794a4cb1ba4"></script>
</head>

<body>

<nav class="site-header sticky-top py-1 bg-dark text-white" >
    <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#" aria-label="Product">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto  text-white" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block text-white" href="/rm">Home</a>
        <a class="py-2 d-none d-md-inline-block text-white" href="/rm/characters">Characters</a>
        <a class="py-2 d-none d-md-inline-block text-white" href="#">Regions</a>
        <a class="py-2 d-none d-md-inline-block text-white" href="#">Locations</a>
        <a class="py-2 d-none d-md-inline-block text-white" href="#">Episodes</a>
        <a class="py-2 d-none d-md-inline-block text-white" href="#">Help</a>
    </div>
</nav>

<div class="container">
    <div class="pt-4">
    	<div class="gcse-search"></div>
    </div>
</div>


