    
    
    
    <div class="align-middle">
        <nav aria-label="Page navigation">
          	<ul class="pagination nav justify-content-end">
                <li class="page-item"><a class="page-link" href="<?php echo $prev; ?>">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="<?php echo $next; ?>">Next</a></li>
          	</ul>
    	</nav>
    </div>